// ---------------------------------------------------------------------------
// Definitions of the fictional demo medical documents. Shared by the PDF
// generator and the database seed so PDFs and extractions stay in sync.
// ALL CONTENT IS FICTIONAL DEMO DATA — no real people, hospitals or policies.
// ---------------------------------------------------------------------------

export interface DemoDocumentDef {
  file: string;
  title: string;
  kind:
    | "MEDICAL_REPORT"
    | "HOSPITAL_INVOICE"
    | "PRESCRIPTION"
    | "DISCHARGE_SUMMARY";
  patientRef: string;
  claimRef?: string;
  caseRef?: string;
  lines: string[];
  signed: boolean;
}

export const DEMO_DOCUMENTS: DemoDocumentDef[] = [
  {
    file: "medical-report-aylin-yilmaz.pdf",
    title: "Medical Report — Istanbul Central Demo Hospital",
    kind: "MEDICAL_REPORT",
    patientRef: "PAT-1001",
    claimRef: "CLM-10245",
    caseRef: "CASE-1020",
    signed: true,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "MEDICAL REPORT",
      "",
      "Hospital: Istanbul Central Demo Hospital",
      "Department: Internal Medicine",
      "Attending Physician: Dr. Kerem Aydin",
      "",
      "Patient Name: Aylin Yilmaz",
      "Date of Birth: 1987-03-14",
      "Nationality: United Kingdom",
      "",
      "Admission Date: 2026-09-18",
      "Presenting Symptoms: severe abdominal pain, nausea, dehydration",
      "Diagnosis: Acute gastroenteritis",
      "Procedures: Intravenous rehydration, blood panel, stool culture",
      "Medications: Ondansetron 4mg, Oral rehydration salts",
      "",
      "Clinical notes: Patient presented at the emergency department after",
      "two days of vomiting and abdominal cramps while travelling. Condition",
      "stabilised within 24 hours of admission. No surgical intervention",
      "required. Recommended rest and hydration for 5 days.",
      "",
      "Signature: Dr. Kerem Aydin (signed)",
    ],
  },
  {
    file: "hospital-invoice-aylin-yilmaz.pdf",
    title: "Hospital Invoice — Istanbul Central Demo Hospital",
    kind: "HOSPITAL_INVOICE",
    patientRef: "PAT-1001",
    claimRef: "CLM-10245",
    caseRef: "CASE-1020",
    signed: false,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "HOSPITAL INVOICE  No. INV-2026-08841",
      "",
      "Hospital: Istanbul Central Demo Hospital",
      "Billing Department",
      "",
      "Patient Name: Aylin Yilmaz",
      "Date of Birth: 1987-03-14",
      "Admission Date: 2026-09-18",
      "Discharge Date: 2026-09-20",
      "",
      "Itemised charges:",
      "  Emergency department admission ........... 6,500.00",
      "  Ward accommodation (2 nights) ............ 9,000.00",
      "  Laboratory tests .......................... 3,250.00",
      "  Medication and consumables ................ 2,100.00",
      "  Physician fees ............................ 4,400.00",
      "",
      "Total Amount Due: 25,250.00 TRY",
      "Currency: TRY",
      "",
      "Payment terms: 30 days. Please quote the invoice number.",
    ],
  },
  {
    file: "discharge-summary-aylin-yilmaz.pdf",
    title: "Discharge Summary — Istanbul Central Demo Hospital",
    kind: "DISCHARGE_SUMMARY",
    patientRef: "PAT-1001",
    claimRef: "CLM-10245",
    caseRef: "CASE-1020",
    signed: true,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "DISCHARGE SUMMARY",
      "",
      "Hospital: Istanbul Central Demo Hospital",
      "Attending Physician: Dr. Kerem Aydin",
      "",
      "Patient Name: Aylin Yilmaz",
      "Date of Birth: 1987-03-14",
      "Admission Date: 2026-09-18",
      "Discharge Date: 2026-09-20",
      "",
      "Diagnosis: Acute gastroenteritis",
      "Procedures: Intravenous rehydration, blood panel, stool culture",
      "Medications: Ondansetron 4mg, Oral rehydration salts",
      "",
      "Condition at discharge: Stable, fit to continue travel after 5 days",
      "of rest. Follow-up with a general practitioner if symptoms recur.",
      "",
      "Signature: Dr. Kerem Aydin (signed)",
    ],
  },
  {
    file: "prescription-aylin-yilmaz.pdf",
    title: "Prescription — Istanbul Central Demo Hospital",
    kind: "PRESCRIPTION",
    patientRef: "PAT-1001",
    claimRef: "CLM-10244",
    signed: true,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "PRESCRIPTION  Rx-2026-5521",
      "",
      "Hospital: Istanbul Central Demo Hospital",
      "Prescribing Doctor: Dr. Kerem Aydin",
      "",
      "Patient Name: Aylin Yilmaz",
      "Date of Birth: 1987-03-14",
      "",
      "Medications Prescribed: Ondansetron 4mg twice daily for 3 days;",
      "Oral rehydration salts after each loose stool",
      "",
      "Policy Number: POL-TR-100944",
      "",
      "Signature: Dr. Kerem Aydin (signed)",
    ],
  },
  {
    file: "medical-report-james-carter.pdf",
    title: "Medical Report — Bosphorus Demo Orthopedic Clinic",
    kind: "MEDICAL_REPORT",
    patientRef: "PAT-1002",
    claimRef: "CLM-10243",
    caseRef: "CASE-1021",
    signed: false,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "MEDICAL REPORT",
      "",
      "Hospital: Bosphorus Demo Orthopedic Clinic",
      "Department: Orthopedics",
      "Attending Physician: Dr. Selin Kaya",
      "",
      "Patient Name: James Carter",
      "Date of Birth: 1979-11-02",
      "Nationality: United States",
      "",
      "Admission Date: 2026-09-21",
      "Presenting Symptoms: right ankle pain and swelling after a fall",
      "Diagnosis: Right lateral malleolus fracture, non-displaced",
      "Procedures: X-ray imaging, cast immobilisation",
      "Medications: Ibuprofen 400mg",
      "",
      "Clinical notes: Patient slipped on stairs near Galata. X-ray confirmed",
      "a non-displaced fracture. Below-knee cast applied; crutches provided.",
      "Fit to fly after orthopedic review in 10 days.",
    ],
  },
  {
    file: "hospital-invoice-james-carter.pdf",
    title: "Hospital Invoice — Bosphorus Demo Orthopedic Clinic",
    kind: "HOSPITAL_INVOICE",
    patientRef: "PAT-1002",
    claimRef: "CLM-10243",
    caseRef: "CASE-1021",
    signed: false,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "HOSPITAL INVOICE  No. INV-2026-09102",
      "",
      "Hospital: Bosphorus Demo Orthopedic Clinic",
      "",
      "Patient Name: James Carter",
      "Date of Birth: 1979-11-02",
      "Admission Date: 2026-09-21",
      "",
      "Itemised charges:",
      "  Emergency consultation ..................... 180.00",
      "  X-ray imaging (2 views) .................... 220.00",
      "  Cast application and materials ............. 340.00",
      "  Crutches .................................... 60.00",
      "",
      "Total Amount Due: 800.00 EUR",
      "Currency: EUR",
    ],
  },
  {
    file: "emergency-report-lena-koch.pdf",
    title: "Emergency Report — Marmara Demo Heart Center",
    kind: "MEDICAL_REPORT",
    patientRef: "PAT-1003",
    caseRef: "CASE-1022",
    signed: true,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "EMERGENCY MEDICAL REPORT",
      "",
      "Hospital: Marmara Demo Heart Center",
      "Department: Cardiology",
      "Attending Physician: Dr. Baran Ozturk",
      "",
      "Patient Name: Lena Koch",
      "Date of Birth: 1964-07-29",
      "Nationality: Germany",
      "",
      "Admission Date: 2026-09-23",
      "Presenting Symptoms: chest pain, shortness of breath",
      "Diagnosis: Unstable angina, ruled out myocardial infarction",
      "Procedures: ECG, troponin series, coronary CT angiography",
      "Medications: Aspirin 100mg, Atorvastatin 40mg, Metoprolol 25mg",
      "",
      "Policy Number: POL-TR-100946",
      "",
      "Clinical notes: Patient admitted from hotel in Sisli with acute chest",
      "pain. Serial troponins negative. CT angiography showed moderate",
      "stenosis; conservative management recommended. Cardiology follow-up",
      "required within one week; fit to fly with medical clearance.",
      "",
      "Signature: Dr. Baran Ozturk (signed)",
    ],
  },
  {
    file: "discharge-summary-lena-koch.pdf",
    title: "Discharge Summary — Marmara Demo Heart Center",
    kind: "DISCHARGE_SUMMARY",
    patientRef: "PAT-1003",
    caseRef: "CASE-1022",
    signed: true,
    lines: [
      "FICTIONAL DEMO DOCUMENT — FOR DEMONSTRATION ONLY",
      "",
      "DISCHARGE SUMMARY",
      "",
      "Hospital: Marmara Demo Heart Center",
      "Attending Physician: Dr. Baran Ozturk",
      "",
      "Patient Name: Lena Koch",
      "Date of Birth: 1964-07-29",
      "Admission Date: 2026-09-23",
      "Discharge Date: 2026-09-25",
      "",
      "Diagnosis: Unstable angina",
      "Procedures: ECG, troponin series, coronary CT angiography",
      "Medications: Aspirin 100mg, Atorvastatin 40mg, Metoprolol 25mg",
      "",
      "Policy Number: POL-TR-100946",
      "",
      "Condition at discharge: Stable on medication. Cardiology review",
      "before flight clearance. Avoid strenuous activity.",
      "",
      "Signature: Dr. Baran Ozturk (signed)",
    ],
  },
];
